/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.viniciuscosta.lojavirtual;

import com.viniciuscosta.lojavirtual.model.*;

public class App {

    public static void main(String[] args) {
        System.out.print("teste\n");
    }
}
